version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: artwork-store
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    networks:
      - app-network

  # Uncomment and configure these services when needed
  # api:
  #   build: ./api
  #   ports:
  #     - "5000:5000"
  #   environment:
  #     - NODE_ENV=production
  #     - DATABASE_URL=postgres://user:password@db:5432/artwork_store
  #   depends_on:
  #     - db
  #   networks:
  #     - app-network

  # db:
  #   image: postgres:13-alpine
  #   container_name: postgres
  #   restart: always
  #   environment:
  #     - POSTGRES_USER=user
  #     - POSTGRES_PASSWORD=password
  #     - POSTGRES_DB=artwork_store
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   networks:
  #     - app-network

  # redis:
  #   image: redis:alpine
  #   container_name: redis
  #   restart: always
  #   volumes:
  #     - redis_data:/data
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge

# volumes:
#   postgres_data:
#   redis_data:
